QT.Qt5Keychain.VERSION = 0.9.90
QT.Qt5Keychain.MAJOR_VERSION = 0
QT.Qt5Keychain.MINOR_VERSION = 9
QT.Qt5Keychain.PATCH_VERSION = 90
QT.Qt5Keychain.name = qt5keychain
QT.Qt5Keychain.defines = 
QT.Qt5Keychain.includes = /Users/TabFitts/nextcloud-toolchain/qt5keychain/include
QT.Qt5Keychain.private_includes =
QT.Qt5Keychain.libs = /Users/TabFitts/nextcloud-toolchain/qt5keychain/lib
QT.Qt5Keychain.depends = core 
